/****
 * OS.NET
 * Copyright (C) 2024 Takym.
 *
 * distributed under the MIT License.
****/

namespace System.Operating.BootstrapLoader.UEFI
{
	public enum EFIStatus : ulong
	{
		EFI_SUCCESS,
		EFI_WARN_UNKNOWN_GLYPH,
		EFI_WARN_DELETE_FAILURE,
		EFI_WARN_WRITE_FAILURE,
		EFI_WARN_BUFFER_TOO_SMALL,
		EFI_WARN_STALE_DATA,
		EFI_WARN_FILE_SYSTEM,
		EFI_WARN_RESET_REQUIRED,

		__ERROR = 0x8000_0000_0000_0000,
		EFI_LOAD_ERROR,
		EFI_INVALID_PARAMETER,
		EFI_UNSUPPORTED,
		EFI_BAD_BUFFER_SIZE,
		EFI_BUFFER_TOO_SMALL,
		EFI_NOT_READY,
		EFI_DEVICE_ERROR,
		EFI_WRITE_PROTECTED,
		EFI_OUT_OF_RESOURCES,
		EFI_VOLUME_CORRUPTED,
		EFI_VOLUME_FULL,
		EFI_NO_MEDIA,
		EFI_MEDIA_CHANGED,
		EFI_NOT_FOUND,
		EFI_ACCESS_DENIED,
		EFI_NO_RESPONSE,
		EFI_NO_MAPPING,
		EFI_TIMEOUT,
		EFI_NOT_STARTED,
		EFI_ALREADY_STARTED,
		EFI_ABORTED,
		EFI_ICMP_ERROR,
		EFI_TFTP_ERROR,
		EFI_PROTOCOL_ERROR,
		EFI_INCOMPATIBLE_VERSION,
		EFI_SECURITY_VIOLATION,
		EFI_CRC_ERROR,
		EFI_END_OF_MEDIA,
		__ERROR_29,
		__ERROR_30,
		EFI_END_OF_FILE,
		EFI_INVALID_LANGUAGE,
		EFI_COMPROMISED_DATA,
		EFI_IP_ADDRESS_CONFLICT,
		EFI_HTTP_ERROR
	}
}
